Controllers/AppointmentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using PeninsulaPhysiotherapy.Data;
using PeninsulaPhysiotherapy.Models;
using System.Security.Claims;

namespace PeninsulaPhysiotherapy.Controllers
{
    [Authorize]
    public class AppointmentsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> userManager;
        private readonly IEmailSender _emailSender;

        public AppointmentsController(
            ApplicationDbContext context, UserManager<AppUser> userManager, IEmailSender emailSender)
        {
            _context = context;
            this.userManager = userManager;
            this._emailSender = emailSender;
        }


        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            var loggedUserName = User.FindFirstValue(ClaimTypes.Name);
            ViewBag.CreateBy = loggedUserName;
            ViewBag.Therapists = new List<AppUser>();
            ViewBag.TherapistName = new Dictionary<string, string>();
            foreach (var user in userManager.Users)
            {
                (ViewBag.TherapistName)[user.Email] = user.UserName;

                if (await userManager.IsInRoleAsync(user, "Therapist"))
                {
                    ViewBag.Therapists.Add(user);
                }
            }
            return _context.AppointmentVM != null ?
                          View(await _context.AppointmentVM.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.AppointmentVM'  is null.");
        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.AppointmentVM == null)
            {
                return NotFound();
            }

            var appointmentVM = await _context.AppointmentVM
                .FirstOrDefaultAsync(m => m.Id == id);
            if (appointmentVM == null)
            {
                return NotFound();
            }

            return View(appointmentVM);
        }

        // GET: Appointments/Create
        public async Task<IActionResult> Create()
        {
            ViewBag.Therapists = new List<AppUser>();
            string resources = "";

            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, "Therapist"))
                {
                    ViewBag.Therapists.Add(user);

                    resources = resources + "," + user.UserName.ToString();
                }
            }
            string events = "";
            if (_context.AppointmentVM != null)
            {
                var appointments = await _context.AppointmentVM.ToListAsync();

                foreach (var appointment in appointments)
                {
                    string title = "Booked";
                    string start = appointment.AppDate.Date.ToString("yyyy-MM-dd") + "T" + appointment.AppDate.TimeOfDay;
                    string end = appointment.AppDate.AddHours(1).Date.ToString("yyyy-MM-dd") + "T" + appointment.AppDate.AddHours(1).TimeOfDay;
                    string resourceId = "";

                    var therapistEmail = appointment.Therapist;
                    var TherapistUser = await userManager.FindByEmailAsync(therapistEmail);
                    if (TherapistUser != null)
                    {
                        resourceId = TherapistUser.UserName;
                    }
                    string record = title + "," + start + "," + end + "," + resourceId;
                    events = events + ";" + record;
                };
            }
            if (events.Length > 0)
            {
                ViewBag.Events = events.Substring(1, events.Length - 1);
            }


            if (resources.Length > 0)
            {
                ViewBag.Resources = resources.Substring(1, resources.Length - 1);
            }


            return View();
        }



        [HttpPost]
        [RequireHttps]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FullName,Gender,Phone,SelectedDate,Therapist,JobType")] AppointmentVM appointmentVM)
        {
            ViewBag.Therapists = new List<AppUser>();
            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, "Therapist"))
                {
                    ViewBag.Therapists.Add(user);
                }
            }
            //Date not null
            if (appointmentVM.SelectedDate == "")
            {
                
                RedirectToAction(nameof(Create));
                ModelState.AddModelError(string.Empty, "Please select a time");
            }
            
            //Post
            if (ModelState.IsValid)
            {
                appointmentVM.JobStatus = "Submited";
                appointmentVM.CreatedBy = User.FindFirstValue(ClaimTypes.Name);
                appointmentVM.AppDate = DateTimeConverter(appointmentVM.SelectedDate);
                var SelectedTherapist = await userManager.FindByNameAsync(appointmentVM.Therapist);
                appointmentVM.Therapist = SelectedTherapist.Email;
                _context.Add(appointmentVM);
                await _context.SaveChangesAsync();
                await _emailSender.SendEmailAsync(User.FindFirstValue(ClaimTypes.Email).ToString(), "Appointment Submited", "You booking is at "+appointmentVM.AppDate.ToString());
                return RedirectToAction(nameof(Index));
            }
            return View(appointmentVM);
        }

        public DateTime DateTimeConverter(string dateFromCal)
        {
            var dateOnly = dateFromCal.Split('T')[0].Split('-');
            int year = int.Parse(dateOnly[0]);
            int month = int.Parse(dateOnly[1]);
            int day = int.Parse(dateOnly[2]);
            var timeOnly = dateFromCal.Split('T')[1].Split('+')[0].Split(':');
            Console.WriteLine(dateOnly);
            Console.WriteLine(timeOnly);
            int hour = int.Parse(timeOnly[0]);
            int minute = int.Parse(timeOnly[1]);
            int second = int.Parse(timeOnly[2]);
            var outDate = new DateTime(year, month, day, hour, minute, second);

            return outDate;
        }



        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.AppointmentVM == null)
            {
                return NotFound();
            }

            var appointmentVM = await _context.AppointmentVM.FindAsync(id);


            if (appointmentVM == null)
            {
                return NotFound();
            }
            else
            {
                var TherapistUser = await userManager.FindByEmailAsync(appointmentVM.Therapist);
                appointmentVM.Therapist = TherapistUser.UserName;
            }
            ViewBag.Therapists = new List<AppUser>();
            string resources = "";

            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(user, "Therapist"))
                {
                    ViewBag.Therapists.Add(user);
                    resources = resources + "," + user.UserName.ToString();
                }
            }
            string events = "";
            if (_context.AppointmentVM != null)
            {
                var appointments = await _context.AppointmentVM.ToListAsync();

                foreach (var appointment in appointments)
                {
                    string title = "Booked";
                    string start = appointment.AppDate.Date.ToString("yyyy-MM-dd") + "T" + appointment.AppDate.TimeOfDay;
                    string end = appointment.AppDate.AddHours(1).Date.ToString("yyyy-MM-dd") + "T" + appointment.AppDate.AddHours(1).TimeOfDay;
                    string resourceId = "";
                    var therapistEmail = appointment.Therapist;
                    var TherapistUser = await userManager.FindByEmailAsync(therapistEmail);
                    if (TherapistUser != null)
                    {
                        resourceId = TherapistUser.UserName;
                    }
                    else
                    {
                        resourceId = therapistEmail;
                    }
                    string record = title + "," + start + "," + end + "," + resourceId;
                    events = events + ";" + record;
                };
            }

            if (events.Length > 0)
            {
                ViewBag.Events = events.Substring(1, events.Length - 1);
            }
            if (resources.Length > 0)
            {
                ViewBag.Resources = resources.Substring(1, resources.Length - 1);
            }


            return View(appointmentVM);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequireHttps]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,Gender,Phone,SelectedDate,Therapist,JobType")] AppointmentVM appointmentVM)
        {
            if (id != appointmentVM.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    appointmentVM.AppDate = DateTimeConverter(appointmentVM.SelectedDate);
                    appointmentVM.JobStatus = "Submited";
                    appointmentVM.CreatedBy = User.FindFirstValue(ClaimTypes.Name);
                    var SelectedTherapist = await userManager.FindByNameAsync(appointmentVM.Therapist);
                    appointmentVM.Therapist = SelectedTherapist.Email;
                    _context.Update(appointmentVM);

Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration.UserSecrets;
using PeninsulaPhysiotherapy.Models;
using System.Data;

namespace PeninsulaPhysiotherapy.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<AppUser> userManager;
        public UsersController(
            RoleManager<IdentityRole> roleManager,
            UserManager<AppUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> ListUsers(string id)
        {
            var users = userManager.Users;


            var roles = roleManager.Roles;
            ViewBag.UserRole = new Dictionary<string, IList<string>>();
            foreach (var user in users)
            {
                var userList = await userManager.GetRolesAsync(user);
                ViewBag.UserRole.Add(user.UserName, userList);
            }
            return View(users);
        }

        public IActionResult EditUser()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {id} cannot be found";
                return View("NotFound");
            }
            var userClaims = await userManager.GetClaimsAsync(user);
            var userRoles = await userManager.GetRolesAsync(user);
            var model = new EditUserVM()
            {
                Id = user.Id,
                UserName = user.UserName,
                Claims = userClaims.Select(c => c.Value).ToList(),
                Roles = userRoles
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserVM editUserVM)
        {
            var user = await userManager.FindByIdAsync(editUserVM.Id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {editUserVM.Id} cannot be found";
                return View("NotFound");
            }
            else
            {
                user.UserName = editUserVM.UserName;
                var result = await userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }
                foreach (IdentityError error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
                return View(editUserVM);
            }
        }



        [HttpGet]
        public async Task<IActionResult> ManageUserRoles(string userId)
        {
            ViewBag.userId = userId;
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            var model = new List<RoleUserVM>();
            foreach(var role in roleManager.Roles)
            {
                var roleUserVM = new RoleUserVM
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };
                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    roleUserVM.IsSelected = true;
                }
                else
                {
                    roleUserVM.IsSelected = false;
                }
                model.Add(roleUserVM);
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> ManageUserRoles(List<RoleUserVM> model, string userId)
        {
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
            }
            var roles = await userManager.GetRolesAsync(user);
            var result = await userManager.RemoveFromRolesAsync(user, roles);
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot remove role");
                return View(model);
            }
            result = await userManager.AddToRolesAsync(user, model.Where(x => x.IsSelected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add role");
                return View(model);
            }
            return RedirectToAction("EditUser", new {Id=userId});
        }

        public async Task<IActionResult> DeleteUser(string id)
        {
            var user= await userManager.FindByIdAsync(id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {id} cannot be found";
                return View("NotFound");
            }
            else
            {
                var result = await userManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View("ListUsers");
            }
        }

    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeninsulaPhysiotherapy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PeninsulaPhysiotherapy.styles.css" asp-append-version="true" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeninsulaPhysiotherapy</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Appointments" asp-action="Index">Bookings</a>
                        </li>
                        @if ((await AuthorizationService.AuthorizeAsync(User, "Management")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="ListUsers">Users</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" id="navListRoles" asp-area="" asp-controller="Administration" asp-action="ListRoles">Roles</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="btn btn-primary" asp-area="" asp-controller="Appointments" asp-action="Create">Make a new Booking</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Feedback">Feedback</a>
                        </li>
                        @if ((await AuthorizationService.AuthorizeAsync(User, "Management")).Succeeded)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Files">Files</a>
                            </li>
                        }
                        


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PeninsulaPhysiotherapy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>